## Chama as Bibliotecas

In [4]:
# Chama as bibliotecas
import sklearn as sk
import numpy as np
import pandas as pd
import matplotlib.pyplot as ptl

# Carrega a base de dados
data = pd.read_csv("CTG.csv")

# Eliminando colunas que não serão utilizadas
data = data.drop(data.columns[0], axis=1)

data.head()

LB  AC  FM  UC  ASTV  MSTV  ALTV  MLTV  DL  DS  ...  Min  Max  Nmax  \
0  120   0   0   0    73   0.5    43   2.4   0   0  ...   62  126     2   
1  132   4   0   4    17   2.1     0  10.4   2   0  ...   68  198     6   
2  133   2   0   5    16   2.1     0  13.4   2   0  ...   68  198     5   
3  134   2   0   6    16   2.4     0  23.0   2   0  ...   53  170    11   
4  132   4   0   5    16   2.4     0  19.9   0   0  ...   53  170     9   

   Nzeros  Mode  Mean  Median  Variance  Tendency  NSP  
0       0   120   137     121        73         1    2  
1       1   141   136     140        12         0    1  
2       1   141   135     138        13         0    1  
3       0   137   134     137        13         1    1  
4       0   137   136     138        11         1    1  

[5 rows x 22 columns]

## Cria o Dataframe de Treino

In [5]:
from sklearn.model_selection import train_test_split

# Cria o dataframe
df_data = pd.DataFrame(data)
df_data.info()

# Separa os dados em treino, teste e validação
x_train, x_temp, y_train, y_temp = train_test_split(df_data, data["NSP"], test_size=0.5, random_state=42)
x_validation, x_test, y_validation, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   LB        2126 non-null   int64  
 1   AC        2126 non-null   int64  
 2   FM        2126 non-null   int64  
 3   UC        2126 non-null   int64  
 4   ASTV      2126 non-null   int64  
 5   MSTV      2126 non-null   float64
 6   ALTV      2126 non-null   int64  
 7   MLTV      2126 non-null   float64
 8   DL        2126 non-null   int64  
 9   DS        2126 non-null   int64  
 10  DP        2126 non-null   int64  
 11  Width     2126 non-null   int64  
 12  Min       2126 non-null   int64  
 13  Max       2126 non-null   int64  
 14  Nmax      2126 non-null   int64  
 15  Nzeros    2126 non-null   int64  
 16  Mode      2126 non-null   int64  
 17  Mean      2126 non-null   int64  
 18  Median    2126 non-null   int64  
 19  Variance  2126 non-null   int64  
 20  Tendency  2126 non-null   int6

## Encontra a Melhor Configuração

In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

higher_acc = -1

# Cria o classificador
for i in ('logistic', 'tanh', 'relu'):
    for j in ('lbfgs', 'sgd', 'adam'):
        for k in ('constant', 'invscaling', 'adaptive'):
            clf = MLPClassifier(hidden_layer_sizes=(100, 100), activation=i, solver=j, learning_rate=k, max_iter=10000, random_state=42)
            clf.fit(x_train, y_train)
            pred = clf.predict(x_validation)
            acc = accuracy_score(y_validation, pred)
            if acc > higher_acc:
                higher_acc = acc
                best_clf = clf
                best_pred = pred
                best_confusion_matrix = confusion_matrix(y_validation, pred)
                best_activation = i
                best_solver = j
                best_learning_rate = k
                
print("Acurácia: ", higher_acc)
print("Função de ativação: ", best_activation)
print("Solver: ", best_solver)
print("Learning rate: ", best_learning_rate)
print("Matriz de confusão: ")
print(best_confusion_matrix)


Acurácia:  0.9792843691148776
Função de ativação:  relu
Solver:  lbfgs
Learning rate:  constant
Matriz de confusão: 
[[411   4   3]
 [  1  72   1]
 [  0   2  37]]
